name: CI   # 워크플로우 이름

on:        # 트리거 정의
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:      # 필수 블록
  build:   # job ID
    runs-on: ubuntu-latest   # 실행 환경
    steps:                   # job 안의 단계
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run a script
        run: echo "Hello, World!"
